spring.application.name=chatbot-service

spring.ai.openai.api-key=sk-xxxxxxxxxxxxxxxx
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.anthropic.api-key=sk-ant-api03-placeholder

server.port=8094

logging.level.root=INFO
logging.level.com.example.chatbot=DEBUG
logging.file.name=logs/chatbot-service.log
