spring.application.name=medical-record-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.data.mongodb.uri=mongodb://localhost:27017/smartcare_db

server.port=8093

logging.level.root=INFO
logging.level.com.example.medicalrecord=DEBUG
logging.file.name=logs/medical-record-service.log
