spring.application.name=medical-record-service

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/smartcare_db}

server.port=8093

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE:http://localhost:8761/eureka}

logging.level.root=INFO
logging.level.com.example.medicalrecord=DEBUG
logging.file.name=logs/medical-record-service.log
