spring.application.name=SmartCare
server.port=8090

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/smartcare
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MongoDB Connection
spring.data.mongodb.uri=mongodb://smartcare-mongo:27017/smartcare_db

jwt.secret=bXktc2VjcmV0LWtleS1teS1zZWNyZXQta2V5LXRoaXMtaXMtbG9uZy1lbm91Z2gta2V5
jwt.expiration=1800000