spring.application.name=api-gateway
spring.main.web-application-type=reactive

server.port=8080

jwt.secret=bXlzdXBlcnNlY3JldGtleTEyMzQ1Njc4OTAxMjM0NTY3ODkw
jwt.expiration=604800000

logging.level.root=INFO
logging.level.com.example.gateway=DEBUG
logging.file.name=logs/api-gateway.log
